### ISSUE TITLE
Provide a button to start digesting manually

### ISSUE THREAD

**Issue by ecuriotto** [Bonitasoft-Community/page_bardigester#1]
It should be nice to give the possibility to choose between auto-digesting and manual digesting (through a button, in the cases when we want more control). Nice to have more than must to have btw

**Comment by pierre-yves-monnet** [comment]
Hello Enrico,
Idea is to keep BarDisgester as simple as possible.
For this usage, use Forklift, he does what you look for! So, I'll close this issue, and if you want to improve forklift, you are welcome!
